// Generates src/shared/emoji.ts from host/emoji.txt so the worker and the host share one list.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const categories = {};
for (const line of readFileSync(join(root, "host/emoji.txt"), "utf8").split("\n")) {
  const t = line.trim();
  if (!t || t.startsWith("#")) continue;
  const [name, rest] = t.split(/:\s*/, 2);
  categories[name] = rest.split(/\s+/).filter(Boolean);
}
const out = `// GENERATED by scripts/gen-emoji.mjs from host/emoji.txt — do not edit by hand.
export const EMOJI_BY_CATEGORY: Record<string, string[]> = ${JSON.stringify(categories, null, 2)};
`;
writeFileSync(join(root, "src/shared/emoji.gen.ts"), out);
console.log(`wrote src/shared/emoji.gen.ts (${Object.values(categories).flat().length} emoji)`);
